/**
 * Push-Config Executor � BullMQ-safe async provisioning
 *
 * Extracted from POST /api/routers/[id]/wireguard push-config handler.
 *
 * ROOT CAUSE FIXES:
 * 1. PHASED FIREWALL: ACCEPT rules applied first, connectivity verified,
 *    DROP rules applied last one-by-one with connectivity check after each.
 *    Rollback all HQ INVESTMENT rules if router becomes unreachable.
 *    Eliminates 504 (was: 16 � 8s timeouts after DROP WAN killed WAN session).
 *
 * 2. DB-FIRST LAN METADATA: lanGateway/lanIp/pools read from DB before
 *    falling back to VPN-derived values. Fixes "missing metadata" on script download.
 *
 * 3. ASYNC EXECUTION: Runs in BullMQ worker, no HTTP timeout constraints.
 */

import { getTenantClient } from "@/lib/tenantPrisma";
import { getMikroTikService, sanitizeMikroTikName, MikroTikService } from "@/lib/mikrotik";
import { wireguardManager } from "@/lib/wireguard";
import { encryptRouterFields, decryptRouterFields } from "@/lib/encryption";
import logger from "@/lib/logger";

const FORBIDDEN_RADIUS_SECRETS = new Set([
    "AUTOGENERATED_BY_AUTO_PUSH",
    "hqinvestment_radius_secret",
    "hqsecret",
]);

function isForbiddenRadiusSecret(value: unknown): boolean {
    return typeof value === "string" && FORBIDDEN_RADIUS_SECRETS.has(value.trim());
}

interface StepResult { step: string; ok: boolean; error?: string; }

export interface PushConfigPayload {
    lanPorts?: string[];
    serverEndpoint?: string;
    serverPort?: number;
}

export interface PushConfigResult {
    success: boolean;
    partialSuccess: boolean;
    tunnelVerified: boolean;
    stepsWithIssues: number;
    stepDetails?: StepResult[];
    message: string;
    routerUnreachableAfterFirewall?: boolean;
    firewallRolledBack?: boolean;
}

async function updateRouterWgFields(
    db: ReturnType<typeof getTenantClient>,
    routerId: string,
    data: Record<string, any>
) {
    const sanitized = Object.fromEntries(Object.entries(data).filter(([, v]) => v !== undefined));
    if (!Object.keys(sanitized).length) return;
    await db.router.update({ where: { id: routerId }, data: encryptRouterFields(sanitized) });
}

export async function executePushConfig(
    routerId: string,
    tenantId: string | null,
    payload: PushConfigPayload
): Promise<PushConfigResult> {
    const db = getTenantClient(tenantId);

    const rawRouter = await db.router.findFirst({
        where: { id: routerId },
        select: {
            id: true, name: true, host: true, tenantId: true,
            port: true, apiPort: true, password: true, username: true,
            radiusSecret: true,
            wgPrivateKey: true, wgPublicKey: true, wgPeerPublicKey: true,
            wgPresharedKey: true, wgTunnelIp: true, wgServerEndpoint: true,
            wgListenPort: true,
            lanIp: true, lanGateway: true, hotspotPoolRange: true,
            pppoePoolRange: true, dns: true, serviceType: true,
        },
    });
    if (!rawRouter) throw new Error(`Router ${routerId} not found`);
    const router = decryptRouterFields(rawRouter) as typeof rawRouter;
    if (isForbiddenRadiusSecret(router.radiusSecret)) {
        throw new Error("RADIUS_SECRET_MISSING: Router has a placeholder or insecure RADIUS secret configured.");
    }

    const stepResults: StepResult[] = [];
    function trackStep(step: string, ok: boolean, err?: unknown): void {
        const error = err instanceof Error ? err.message : err ? String(err) : undefined;
        stepResults.push({ step, ok, error });
        if (!ok) logger.warn(`[PUSH-CONFIG] Step failed: ${step}`, { error });
    }

    const wgServerIp = await wireguardManager.getServerIp();
    const subnetPrefix = wgServerIp.split(".").slice(0, 3).join(".");
    let tunnelIp = router.wgTunnelIp;
    if (!tunnelIp || !tunnelIp.startsWith(`${subnetPrefix}.`)) tunnelIp = `${subnetPrefix}.200`;

    // DB-first LAN metadata (canonical source set by Setup Wizard)
    const tunnelParts = tunnelIp.split(".");
    const vpnDerivedPrefix = `${tunnelParts[0]}.10.${tunnelParts[2] || "0"}`;
    const dbLanGateway  = router.lanGateway  as string | null;
    const dbLanIp       = router.lanIp       as string | null;
    const dbHsPool      = router.hotspotPoolRange as string | null;
    const dbPpoePool    = router.pppoePoolRange   as string | null;
    const dbDns         = router.dns              as string | null;

    const lanGateway = dbLanGateway || `${vpnDerivedPrefix}.1`;
    const lanCidr    = dbLanIp      || `${lanGateway}/24`;
    const lanPrefix  = lanGateway.split(".").slice(0, 3).join(".");
    const lanNetwork = `${lanPrefix}.0/24`;
    const listenPort = router.wgListenPort || 51820;

    const hsPoolStart   = dbHsPool?.split("-")[0]   || `${lanPrefix}.10`;
    const hsPoolEnd     = dbHsPool?.split("-")[1]   || `${lanPrefix}.149`;
    const ppoePoolStart = dbPpoePool?.split("-")[0] || `${lanPrefix}.150`;
    const ppoePoolEnd   = dbPpoePool?.split("-")[1] || `${lanPrefix}.250`;

    // Server endpoint
    const appUrl = process.env.APP_URL || process.env.NEXT_PUBLIC_APP_URL;
    let serverEndpoint = payload.serverEndpoint || router.wgServerEndpoint || process.env.WG_SERVER_ENDPOINT || "";
    if (!serverEndpoint && appUrl) {
        try { serverEndpoint = new URL(appUrl).hostname; }
        catch { serverEndpoint = appUrl.replace(/^https?:\/\//, "").split("/")[0]; }
    }
    if (!serverEndpoint) serverEndpoint = process.env.SERVER_PUBLIC_IP || "vpn.billing-system.local";
    const serverPort = payload.serverPort || parseInt(process.env.WG_SERVER_PORT || "51820");
    const lanPorts: string[] = Array.isArray(payload.lanPorts) ? payload.lanPorts : [];

    const service = await getMikroTikService(routerId, tenantId);

    let criticalStepFailed = false;
    const runApi = async (category: string, ep: string, method: string = "GET", data?: any, critical = false) => {
        if (criticalStepFailed) return null;
        try {
            return await service.apiRequestPublic(ep, method as any, data);
        } catch (e: any) {
            const msg = e.message || String(e);
            if (msg.includes("already") || msg.includes("no such")) return null;
            trackStep(category + ": " + ep, false, msg);
            if (critical) {
                criticalStepFailed = true;
                throw new Error(`Critical phase failed [${category}]: ${msg}`);
            }
            return null;
        }
    };
    const runApiSafe = async (ep: string, method: string = "GET", data?: any) => {
        try { return await service.apiRequestPublic(ep, method as any, data); } catch {}
    };


    // -- STEP 0: Cleanup -------------------------------------------------------
    logger.info("[PUSH-CONFIG] Cleaning up old HQ INVESTMENT configs...");
    for (const ep of ["/ip/firewall/filter", "/ip/firewall/nat", "/ip/route", "/ip/address"]) {
        try {
            const items = await service.apiRequestPublic(ep);
            if (Array.isArray(items)) {
                for (const item of items) {
                    if (item.comment?.includes("HQ INVESTMENT")) {
                        await runApiSafe(`${ep}/${item[".id"]}`, "DELETE");
                    }
                }
            }
        } catch {}
    }

    // -- STEP 1: Basic setup ---------------------------------------------------
    if (router.username && router.password) {
        try {
            const users = await service.apiRequestPublic("/user");
            if (Array.isArray(users)) {
                const ex = users.find((u: any) => u.name === router.username || u.name === "admin");
                if (ex) {
                    await service.apiRequestPublic("/user", "PATCH", { ".id": ex[".id"], name: router.username, password: router.password });
                } else {
                    await service.apiRequestPublic("/user", "PUT", { name: router.username, password: router.password, group: "full", comment: "Management User - DO NOT DELETE" });
                }
            }
        } catch {}
    }
    await runApi("MANAGEMENT", "/system/identity", "PATCH", { name: router.name });
    await runApi("MANAGEMENT", "/ip/dns", "PATCH", { servers: "8.8.8.8,8.8.4.4", "allow-remote-requests": "yes" });
    await runApi("MANAGEMENT", "/system/ntp/client", "PATCH", { enabled: "yes", servers: "pool.ntp.org" });

    // -- STEP 2: Bridge + Hotspot + PPPoE + DHCP ------------------------------
    logger.info("[PUSH-CONFIG] Setting up Bridge, Hotspot & PPPoE...");
    let lanBridgeName = "bridge-lan";
    let bridgeExists = false;
    try {
        const bridges = await service.apiRequestPublic("/interface/bridge");
        if (Array.isArray(bridges) && bridges.length > 0) {
            const lb = bridges.find((b: any) => !b.name.toLowerCase().startsWith("wan") && b.name !== "wan-bridge");
            if (lb) { lanBridgeName = lb.name; bridgeExists = true; }
        }
    } catch {}

    if (!bridgeExists) {
        await runApi("BRIDGE", "/interface/bridge", "PUT", { name: lanBridgeName, "protocol-mode": "none", comment: "HQ INVESTMENT LAN Bridge - Hotspot & PPPoE" }, true);
    } else {
        try {
            const bl = await service.apiRequestPublic("/interface/bridge");
            const ex = Array.isArray(bl) ? bl.find((b: any) => b.name === lanBridgeName) : null;
            if (ex?.["\.id"]) await runApi("BRIDGE", `/interface/bridge/${ex["\.id"]}`, "PATCH", { "protocol-mode": "none" });
        } catch {}
    }

    // Bridge ports
    if (lanPorts.length > 0) {
        try {
            const allInterfaces = await service.apiRequestPublic("/interface");
            const existingInterfaces = Array.isArray(allInterfaces) ? new Set(allInterfaces.map((i: any) => i.name)) : new Set();
            const ep = await service.apiRequestPublic("/interface/bridge/port");
            for (const portName of lanPorts) {
                if (!portName || portName === "ether1" || portName.includes("wan")) continue;
                if (!existingInterfaces.has(portName)) {
                    logger.warn(`[PUSH-CONFIG] Skipping port ${portName} as it does not exist on router ${router.name}`);
                    continue;
                }
                const ex = Array.isArray(ep) ? ep.find((p: any) => p.interface === portName) : null;
                if (ex) {
                    if (ex.bridge !== lanBridgeName) {
                        // Only change ownership if explicitly requested
                        await runApiSafe(`/interface/bridge/port/${ex[".id"]}`, "PATCH", { bridge: lanBridgeName, comment: "HQ INVESTMENT Auto-Added" });
                    }
                } else {
                    await runApiSafe("/interface/bridge/port", "PUT", { bridge: lanBridgeName, interface: portName, comment: "HQ INVESTMENT Auto-Added" });
                }
            }
        } catch {}
    }

    // Remove WAN interfaces from LAN bridge
    try {
        const allBP = await service.apiRequestPublic("/interface/bridge/port");
        if (Array.isArray(allBP)) {
            const wanPat = /^(ether1|sfp[\d-]|lte[\d-]|wan)/i;
            for (const bp of allBP) {
                if (bp.bridge === lanBridgeName && wanPat.test(bp.interface) && !lanPorts.includes(bp.interface)) {
                    await runApiSafe(`/interface/bridge/port/${bp[".id"]}`, "DELETE");
                }
            }
        }
    } catch {}

    // Clean stale HQ addresses, DHCP, pools, hotspot (Strict Ownership)
    for (const ep of ["/ip/address", "/ip/dhcp-server", "/ip/dhcp-server/network", "/ip/pool", "/ip/hotspot"]) {
        try {
            const items = await service.apiRequestPublic(ep);
            if (Array.isArray(items)) {
                for (const item of items) {
                    const isHqComment = item.comment?.includes("HQ INVESTMENT");
                    const isHqName = (ep === "/ip/pool" && (item.name?.includes("hs-pool") || item.name?.includes("pppoe-pool"))) ||
                                     (ep === "/ip/dhcp-server" && item.name?.startsWith("dhcp-")) ||
                                     (ep === "/ip/hotspot" && item.name?.startsWith("hq-hotspot"));
                    // Only delete if we are certain it belongs to us. We never delete "defconf" or UNKNOWN resources.
                    if (isHqComment || isHqName) {
                        await runApiSafe(`${ep}/${item[".id"]}`, "DELETE");
                    }
                }
            }
        } catch {}
    }

    const safeRouterName = sanitizeMikroTikName(router.name);
    const safeRouterNameLower = sanitizeMikroTikName(router.name.toLowerCase());
    const hotspotProfileName = `hsprof-${safeRouterNameLower}`;

    await runApi("LAN/POOL/HOTSPOT", "/ip/hotspot/profile", "PUT", { name: hotspotProfileName, "hotspot-address": lanGateway, "dns-name": `${safeRouterNameLower}.hotspot`, "html-directory": "hotspot", "login-by": "http-chap,https,cookie", "http-cookie-lifetime": "3d", "use-radius": "yes" }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/dns/static", "PUT", { name: `${safeRouterNameLower}.hotspot`, address: lanGateway, comment: "HQ INVESTMENT Hotspot DNS" }, true);

    // Secure all existing hotspot profiles
    try {
        const profiles = await service.apiRequestPublic("/ip/hotspot/profile");
        if (Array.isArray(profiles)) {
            for (const prof of profiles) {
                if (prof["use-radius"] !== "yes" || (prof["login-by"] || "").includes("mac")) {
                    await service.apiRequestPublic(`/ip/hotspot/profile/${prof[".id"]}`, "PATCH", { "use-radius": "yes", "login-by": "http-chap,https,cookie" });
                }
            }
        }
    } catch {}

    await runApi("LAN/POOL/HOTSPOT", "/ip/pool", "PUT", { name: `hs-pool-${safeRouterName}`, ranges: `${hsPoolStart}-${hsPoolEnd}` }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/pool", "PUT", { name: `pppoe-pool-${safeRouterName}`, ranges: `${ppoePoolStart}-${ppoePoolEnd}` }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/address", "PUT", { address: lanCidr, interface: lanBridgeName, comment: "HQ INVESTMENT Hotspot LAN" }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/dhcp-server/network", "PUT", { address: lanNetwork, gateway: lanGateway, "dns-server": dbDns || "8.8.8.8,1.1.1.1" }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/dhcp-server", "PUT", { name: `dhcp-${safeRouterName}`, interface: lanBridgeName, "address-pool": `hs-pool-${safeRouterName}`, "lease-time": "1h", disabled: "no" }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/hotspot", "PUT", { name: `hotspot-${safeRouterName}`, interface: lanBridgeName, "address-pool": `hs-pool-${safeRouterName}`, profile: hotspotProfileName, disabled: "no" }, true);
    await runApi("PPPOE", "/ppp/profile", "PUT", { name: `pppoe-profile-${safeRouterName}`, "local-address": lanGateway, "remote-address": `pppoe-pool-${safeRouterName}`, "dns-server": dbDns || "8.8.8.8,1.1.1.1", "use-encryption": "yes", "use-radius": "yes" }, true);
    await runApi("PPPOE", "/ppp/aaa", "PATCH", { "use-radius": "yes", "accounting": "yes" });
    await runApi("PPPOE", "/interface/pppoe-server/server", "PUT", { "service-name": `pppoe-svc-${safeRouterName}`, interface: lanBridgeName, "default-profile": `pppoe-profile-${safeRouterName}`, "one-session-per-host": "yes", disabled: "no" }, true);

    // -- STEP 3: WireGuard VPN -------------------------------------------------
    logger.info("[PUSH-CONFIG] Setting up WireGuard VPN...");
    try { await wireguardManager.addPeer(router.wgPublicKey!, tunnelIp, router.wgPresharedKey || undefined); trackStep("WireGuard: add peer on server", true); }
    catch (e: any) { trackStep("WireGuard: add peer on server", false, e); }

    try {
        await service.apiRequestPublic("/interface/wireguard", "PUT", { name: "wg-hq", "listen-port": String(listenPort), "private-key": router.wgPrivateKey, disabled: "no", comment: "HQ INVESTMENT VPN Interface" });
        trackStep("WireGuard: create wg-hq interface", true);
    } catch (e: any) {
        if (e.message?.includes("already")) {
            try {
                const wi = await service.apiRequestPublic("/interface/wireguard");
                if (Array.isArray(wi)) { const ex = wi.find((i: any) => i.name === "wg-hq"); if (ex?.[".id"]) await service.apiRequestPublic(`/interface/wireguard/${ex[".id"]}`, "PATCH", { "private-key": router.wgPrivateKey }); }
                trackStep("WireGuard: create wg-hq interface", true);
            } catch (pe) { trackStep("WireGuard: create wg-hq interface", false, pe); }
        } else { trackStep("WireGuard: create wg-hq interface", false, e); }
    }

    try {
        const addrs = await service.apiRequestPublic("/ip/address");
        if (Array.isArray(addrs)) { for (const a of addrs) { if (a.interface === "wg-hq") await runApiSafe(`/ip/address/${a[".id"]}`, "DELETE"); } }
    } catch {}
    await runApi("LAN/POOL/HOTSPOT", "/ip/address", "PUT", { address: `${tunnelIp}/24`, interface: "wg-hq", comment: "HQ INVESTMENT VPN Address" }, true);

    try {
        const oldPeers = await service.apiRequestPublic("/interface/wireguard/peers");
        if (Array.isArray(oldPeers)) {
            for (const p of oldPeers) {
                if (p.comment?.includes("HQ INVESTMENT") || p.interface === "wg-hq") await runApiSafe(`/interface/wireguard/peers/${p[".id"]}`, "DELETE");
            }
        }
    } catch {}
    
    const serverWgPublicKey = router.wgPeerPublicKey ?? await wireguardManager.getServerPublicKey() ?? process.env.WG_SERVER_PUBLIC_KEY;
    if (!serverWgPublicKey) {
        throw new Error("Server WireGuard public key is unavailable; refusing configuration push");
    }

    try {
        await service.apiRequestPublic("/interface/wireguard/peers", "PUT", { interface: "wg-hq", "public-key": serverWgPublicKey, ...(router.wgPresharedKey ? { "preshared-key": router.wgPresharedKey } : {}), "allowed-address": `${subnetPrefix}.0/24`, "endpoint-address": serverEndpoint, "endpoint-port": String(serverPort), "persistent-keepalive": "25s", comment: "HQ INVESTMENT ISP Server" });
        
        // Post-write verification
        const peerCheck = await service.apiRequestPublic("/interface/wireguard/peers");
        const peer = Array.isArray(peerCheck) ? peerCheck.find((p: any) => p["public-key"] === serverWgPublicKey && p.interface === "wg-hq") : null;
        if (!peer) throw new Error("WireGuard peer was not created on the router.");
        if (!peer["allowed-address"]?.includes(`${subnetPrefix}.0/24`)) throw new Error("WireGuard peer allowed-address mismatch.");
        
        trackStep("WireGuard: add server peer", true);
    } catch (e: any) {
        if (!e.message?.includes("already")) {
            trackStep("WireGuard: add server peer", false, e);
            criticalStepFailed = true;
            throw new Error(`Critical phase failed [WireGuard Peer]: ${e.message}`);
        }
        else trackStep("WireGuard: add server peer", true);
    }

    // -- STEP 4-6: NAT + Route -------------------------------------------------
    const restPort = router.apiPort || (router.port === 8728 || router.port === 8729 ? 80 : router.port) || 80;
    
    let wanInterface = "ether1";
    try {
        const routes = await service.apiRequestPublic("/ip/route");
        if (Array.isArray(routes)) {
            const dflt = routes.find((r: any) => r["dst-address"] === "0.0.0.0/0" && !r.disabled && r.active !== "false");
            if (dflt?.interface) { wanInterface = dflt.interface; logger.info(`[PUSH-CONFIG] Detected WAN: ${wanInterface}`); }
        }
    } catch {}

    logger.info("[PUSH-CONFIG] Setting up NAT & Route...");
    // Ensure WAN interface list exists and wanInterface is added
    await runApiSafe("/interface/list", "PUT", { name: "WAN", comment: "HQ INVESTMENT WAN" });
    try {
        const listMembers = await service.apiRequestPublic("/interface/list/member");
        const wanMember = Array.isArray(listMembers) ? listMembers.find((m: any) => m.list === "WAN" && m.interface === wanInterface) : null;
        if (!wanMember) {
            await runApiSafe("/interface/list/member", "PUT", { list: "WAN", interface: wanInterface, comment: "HQ INVESTMENT WAN port" });
        }
    } catch {}

    await runApi("LAN/POOL/HOTSPOT", "/ip/firewall/nat", "PUT", { chain: "srcnat", action: "masquerade", "out-interface-list": "WAN", comment: "NAT for Internet - HQ INVESTMENT", "place-before": "0" }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/route", "PUT", { "dst-address": `${subnetPrefix}.0/24`, gateway: "wg-hq", comment: "WireGuard route - HQ INVESTMENT" }, true);

    // -- STEP 7: RADIUS & CoA --------------------------------------------------
    logger.info("[PUSH-CONFIG] Setting up RADIUS...");
    try {
        const oldR = await service.apiRequestPublic("/radius");
        if (Array.isArray(oldR)) { for (const r of oldR) { if (r.comment?.includes("HQ INVESTMENT")) await runApiSafe(`/radius/${r[".id"]}`, "DELETE"); } }
    } catch {}

    let currentRadiusSecret = router.radiusSecret as string | undefined;
    if (!currentRadiusSecret) {
        logger.error(`[PUSH-CONFIG] RADIUS_SECRET_MISSING for router ${routerId}`);
        throw new Error("RADIUS_SECRET_MISSING: Router does not have a RADIUS secret configured.");
    }
    try { await service.apiRequestPublic("/radius", "PUT", { address: wgServerIp, secret: currentRadiusSecret, service: "hotspot,ppp", "authentication-port": "1812", "accounting-port": "1813", timeout: "10000ms", "src-address": tunnelIp, comment: "HQ INVESTMENT RADIUS" }); trackStep("RADIUS: register server on router", true); }
    catch (e: any) { trackStep("RADIUS: register server on router", false, e); }
    try { await service.apiRequestPublic("/radius/incoming", "PATCH", { accept: "yes", port: "3799" }); trackStep("RADIUS: enable CoA (incoming)", true); }
    catch (e: any) { trackStep("RADIUS: enable CoA (incoming)", false, e); }

    // -- STEP 7b: Walled Garden ------------------------------------------------
    logger.info("[PUSH-CONFIG] Setting up Walled Garden...");
    const billingHost = (process.env.WG_SERVER_ENDPOINT || process.env.NEXT_PUBLIC_API_URL?.replace(/^https?:\/\//, "") || wgServerIp).split(":")[0];
    for (const ep of ["/ip/hotspot/walled-garden", "/ip/hotspot/walled-garden/ip"]) {
        try { const items = await service.apiRequestPublic(ep); if (Array.isArray(items)) { for (const e of items) { if (e.comment?.includes("HQ INVESTMENT")) await runApiSafe(`${ep}/${e[".id"]}`, "DELETE"); } } } catch {}
    }
    await runApi("LAN/POOL/HOTSPOT", "/ip/hotspot/walled-garden", "PUT", { "dst-host": billingHost, action: "allow", comment: "Billing Portal - HQ INVESTMENT" }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/hotspot/walled-garden/ip", "PUT", { "dst-address": wgServerIp, action: "accept", comment: "Billing Portal IP - HQ INVESTMENT" }, true);
    await runApi("LAN/POOL/HOTSPOT", "/ip/hotspot/walled-garden/ip", "PUT", { "dst-address": `${subnetPrefix}.0/24`, action: "accept", comment: "VPN Subnet - HQ INVESTMENT" }, true);

    // -- STEP 8: Phased Firewall -----------------------------------------------
    logger.info("[PUSH-CONFIG] Phase 3: Applying phased firewall lockdown...");

    const hqServerIp = process.env.SERVER_PUBLIC_IP || serverEndpoint;
    const isValidIp = /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(hqServerIp);

    const acceptRules: Record<string, string>[] = [
        { chain: "input", protocol: "udp", "dst-port": String(listenPort), action: "accept", comment: "Allow WireGuard - HQ INVESTMENT" },
        { chain: "input", "in-interface": "wg-hq", action: "accept", comment: "Allow WireGuard interface input - HQ INVESTMENT" },
        { chain: "input", protocol: "icmp", "src-address": `${subnetPrefix}.0/24`, action: "accept", comment: "Allow ICMP from VPN - HQ INVESTMENT" },
        { chain: "input", protocol: "tcp", "dst-port": String(restPort), "src-address": `${subnetPrefix}.0/24`, action: "accept", comment: "Allow REST API from VPN - HQ INVESTMENT" },
        { chain: "input", protocol: "tcp", "dst-port": "8291", "src-address": `${subnetPrefix}.0/24`, action: "accept", comment: "Allow Winbox from VPN - HQ INVESTMENT" },
        { chain: "input", protocol: "udp", "dst-port": "3799", "src-address": `${subnetPrefix}.0/24`, action: "accept", comment: "Allow RADIUS CoA from VPN - HQ INVESTMENT" },
        { chain: "input", protocol: "tcp", "dst-port": "80,443", "src-address": `${subnetPrefix}.0/24`, action: "accept", comment: "Allow Web from VPN - HQ INVESTMENT" },
        { chain: "input", protocol: "tcp", "dst-port": "8728,8729", "src-address": `${subnetPrefix}.0/24`, action: "accept", comment: "Allow API from VPN - HQ INVESTMENT" },
        { chain: "input", protocol: "udp", "dst-port": "53,67", "in-interface": lanBridgeName, action: "accept", comment: "Allow DNS & DHCP from LAN - HQ INVESTMENT" },
        { chain: "input", protocol: "icmp", action: "accept", comment: "Allow Ping - HQ INVESTMENT" },
        { chain: "input", "connection-state": "established,related", action: "accept", comment: "Allow Established Input - HQ INVESTMENT" },
        { chain: "input", "in-interface": lanBridgeName, protocol: "tcp", "dst-port": "80,443", action: "accept", comment: "Allow Hotspot Captive Portal - HQ INVESTMENT" },
        { chain: "input", "in-interface": lanBridgeName, protocol: "udp", "dst-port": "67", action: "accept", comment: "Allow Hotspot DHCP - HQ INVESTMENT" },
        { chain: "input", "in-interface": lanBridgeName, protocol: "udp", "dst-port": "53", action: "accept", comment: "Allow Hotspot DNS - HQ INVESTMENT" },
        { chain: "forward", "in-interface": "all-ppp", "out-interface": "ether1", action: "accept", comment: "Allow PPPoE to Internet - HQ INVESTMENT" },
        { chain: "forward", "connection-state": "established,related", action: "accept", comment: "Allow Established Forward - HQ INVESTMENT" },
        { chain: "forward", "in-interface": "wg-hq", action: "accept", comment: "Allow WG traffic - HQ INVESTMENT" },
        { chain: "forward", "out-interface": "wg-hq", action: "accept", comment: "Allow WG return - HQ INVESTMENT" },
    ];
    if (isValidIp) { acceptRules.push({ chain: "input", "in-interface": wanInterface, protocol: "tcp", "dst-port": `${restPort},8728,8729,8291`, "src-address": hqServerIp, action: "accept", comment: "HQ Server Management - HQ INVESTMENT" }); }

    const dropRules: Record<string, string>[] = [
        { chain: "input", "in-interface": wanInterface, action: "drop", comment: "Drop WAN input - HQ INVESTMENT" },
        { chain: "forward", "in-interface": lanBridgeName, action: "drop", comment: "Drop unauthenticated LAN forward - HQ INVESTMENT" },
    ];

    // Test connectivity over the new WireGuard VPN tunnel IP to ensure it's routing
    // properly before we drop WAN access.
    async function testVpnConnectivity(): Promise<boolean> {
        try {
            const vpnService = new MikroTikService({
                host: tunnelIp || "",
                port: router.apiPort || router.port || 8728,
                username: router.username || "admin",
                password: router.password || ""
            }, routerId, rawRouter?.tenantId || "");
            await vpnService.apiRequestPublic("/system/identity", "GET");
            return true;
        } catch (err: any) {
            logger.warn(`[PUSH-CONFIG] VPN Connectivity test failed: ${err.message}`);
            return false;
        }
    }
    
    async function rollbackFirewall(): Promise<void> {
        try {
            const rules = await service.apiRequestPublic("/ip/firewall/filter");
            if (Array.isArray(rules)) {
                for (const rule of rules) {
                    if (rule.comment?.includes("HQ INVESTMENT")) await runApiSafe(`/ip/firewall/filter/${rule[".id"]}`, "DELETE");
                }
            }
            logger.warn("[PUSH-CONFIG] Firewall rollback completed.");
        } catch (e) { logger.error("[PUSH-CONFIG] Firewall rollback FAILED:", { error: String(e) }); }
    }

    // Phase A: ACCEPT rules
    let fwAcceptFail = 0;
    for (const rule of [...acceptRules].reverse()) {
        try { await service.apiRequestPublic("/ip/firewall/filter", "PUT", { ...rule, "place-before": "0" }); }
        catch (e: any) { if (!e.message?.includes("already")) fwAcceptFail++; }
    }

    // Phase B: connectivity before DROP
    let routerUnreachableAfterFirewall = false;
    let firewallRolledBack = false;
    let fwDropFail = 0;
    // Wait a few seconds to let WireGuard tunnel establish before testing
    await new Promise(res => setTimeout(res, 3000));
    
    const preDropReachable = await testVpnConnectivity();
    if (!preDropReachable) {
        logger.error("[PUSH-CONFIG] VPN ROUTER_UNREACHABLE before DROP rules. Rolling back.");
        await rollbackFirewall();
        trackStep("Firewall: pre-DROP VPN connectivity", false, "Router unreachable over VPN before DROP rules");
        routerUnreachableAfterFirewall = true;
        firewallRolledBack = true;
    } else {
        // Phase C: DROP rules one by one
        for (const dropRule of [...dropRules].reverse()) {
            try {
                await service.apiRequestPublic("/ip/firewall/filter", "PUT", { ...dropRule, "place-before": "0" });
                logger.info(`[PUSH-CONFIG] DROP rule applied: ${dropRule.comment}`);
            } catch (e: any) { if (!e.message?.includes("already")) fwDropFail++; }

            const stillReachable = await testVpnConnectivity();
            if (!stillReachable) {
                routerUnreachableAfterFirewall = true;
                logger.error(`[PUSH-CONFIG] ROUTER_UNREACHABLE_AFTER_FIREWALL (VPN) — after: ${dropRule.comment}`);
                await rollbackFirewall();
                firewallRolledBack = true;
                trackStep("Firewall: DROP rule VPN connectivity", false, `ROUTER_UNREACHABLE_AFTER_FIREWALL over VPN after: ${dropRule.comment}. All rules rolled back.`);
                break;
            }
        }
        if (!routerUnreachableAfterFirewall) {
            trackStep("Firewall: DROP rules", fwDropFail === 0);
        }
    }
    
    if (!routerUnreachableAfterFirewall) {
        const fwFail = fwAcceptFail + fwDropFail;
        trackStep("Firewall: push all rules", fwFail === 0, fwFail > 0 ? `${fwFail} rule(s) failed` : undefined);
        logger.info(`[PUSH-CONFIG] Firewall lockdown applied. Accept failures: ${fwAcceptFail}, Drop failures: ${fwDropFail}`);
    }

    // -- Verify tunnel ---------------------------------------------------------
    await new Promise(resolve => setTimeout(resolve, 1000));
    const tunnelVerified = router.wgPublicKey
        ? await wireguardManager.checkPeerHandshake(router.wgPublicKey).catch(() => false)
        : false;

    // -- Persist to DB ---------------------------------------------------------
    const updateData: Record<string, any> = {
        wgEnabled: true, wgConfiguredAt: new Date(),
        lanIp:            dbLanIp      || lanCidr,
        lanGateway:       dbLanGateway || lanGateway,
        hotspotPoolRange: dbHsPool     || `${hsPoolStart}-${hsPoolEnd}`,
        pppoePoolRange:   dbPpoePool   || `${ppoePoolStart}-${ppoePoolEnd}`,
        dns:              dbDns         || "8.8.8.8,1.1.1.1",
        serviceType:      (rawRouter as any).serviceType || "both",
    };
    if (tunnelVerified) updateData.host = tunnelIp;
    else logger.warn(`[PUSH-CONFIG] Peer ${tunnelIp} handshake not confirmed. Keeping original host IP.`);
    await updateRouterWgFields(db, routerId, updateData);

    // -- Audit log -------------------------------------------------------------
    const failedSteps = stepResults.filter(s => !s.ok);
    const hasCriticalFailure = criticalStepFailed || failedSteps.some(s => s.step.includes("WireGuard") || s.step.includes("Firewall") || s.step.includes("RADIUS"));
    await db.routerLog.create({
        data: {
            routerId,
            action: failedSteps.length === 0 ? "wireguard_pushed" : "wireguard_pushed_partial",
            details: `WireGuard config pushed to ${router.name}. ${
                failedSteps.length === 0 ? "All steps succeeded." : `${failedSteps.length} step(s) had issues: ${failedSteps.map(s => s.step).join(", ")}.`
            }${tunnelVerified ? ` Tunnel IP: ${tunnelIp}.` : " Tunnel verification failed."}${firewallRolledBack ? " FIREWALL ROLLED BACK." : ""}`,
            status: failedSteps.length === 0 ? "success" : "partial",
        },
    });

    return {
        success: !hasCriticalFailure,
        partialSuccess: failedSteps.length > 0 && !hasCriticalFailure,
        tunnelVerified,
        stepsWithIssues: failedSteps.length,
        stepDetails: failedSteps.length > 0 ? failedSteps : undefined,
        routerUnreachableAfterFirewall,
        firewallRolledBack,
        message: hasCriticalFailure
            ? `Push-config completed with ${failedSteps.length} critical failure(s). Check step details and retry.`
            : firewallRolledBack
                ? `Services configured on ${router.name}, but firewall was rolled back (router unreachable after DROP WAN). WireGuard tunnel may need manual verification. Tunnel IP: ${tunnelIp}.`
                : failedSteps.length > 0
                    ? `WireGuard configured on ${router.name} with ${failedSteps.length} minor issue(s). Core functions operational.${tunnelVerified ? ` Tunnel IP: ${tunnelIp}.` : ""}`
                    : tunnelVerified
                        ? `WireGuard configured and tunnel established on ${router.name}. Tunnel IP: ${tunnelIp}.`
                        : `WireGuard configured on ${router.name}, but tunnel handshake not yet confirmed. Keeping original host IP.`,
    };
}
