import { NextRequest } from "next/server";
import { getTenantClient } from "@/lib/tenantPrisma";
import { errorResponse } from "@/lib/auth";
import { requirePermission } from "@/lib/rbac";
import { canAccessTenant } from "@/lib/tenant";
import { decryptRouterFields, encrypt } from "@/lib/encryption";
import { deriveLanNetworkCidr, generateRouterAdminPassword, generateRadiusSecret } from "@/lib/routerProvisioning";
import { buildRouterWizardScript, buildHotspotFlowEnforcementLines, normalizeWizardScriptInputs } from "@/lib/routerWizardScriptBuilder";

const FORBIDDEN_RADIUS_SECRETS = new Set([
    "AUTOGENERATED_BY_AUTO_PUSH",
    "hqinvestment_radius_secret",
    "hqsecret",
]);

function isForbiddenRadiusSecret(value: unknown): boolean {
    return typeof value === "string" && FORBIDDEN_RADIUS_SECRETS.has(value.trim());
}

// Simple sanitizer for wireless passphrases embedded into RouterOS scripts.
function sanitizePassphrase(p: unknown): string {
    if (!p || typeof p !== 'string') return '';
    return p.replace(/["'\\]/g, '').substring(0, 64);
}

function parseRequestedLanInterfaces(req: NextRequest): string[] {
    const rawValue = req.nextUrl.searchParams.get('selectedInterfaces') || req.nextUrl.searchParams.get('lanPorts') || '';
    const values = rawValue
        .split(',')
        .map((value) => value.trim())
        .filter(Boolean);

    return normalizeWizardScriptInputs({ selectedInterfaces: values }).selectedInterfaces;
}

import logger from "@/lib/logger";

/**
 * GET /api/routers/[id]/script
 * 
 * Generates a MikroTik RouterOS script that the user can copy and paste 
 * into their router terminal to automatically configure it for HQ INVESTMENT.
 */
export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
    try {
        const guard = requirePermission(req, "routers:read");
        if (guard.error) return guard.error;
        const userPayload = guard.user;
        const db = getTenantClient(userPayload);

        const { id } = await params;
        const routerRaw = await db.router.findUnique({ where: { id } });

        if (!routerRaw) return errorResponse("Router not found", 404);
        if (!canAccessTenant(userPayload, routerRaw.tenantId)) {
            return errorResponse("Unauthorized", 403);
        }

        // P0 Validation layer: Validate required LAN/Subnet/DNS fields
        // RC-2 FIX: hotspotPoolRange and pppoePoolRange are now conditional on
        // serviceType so that hotspot-only routers don't need pppoePoolRange
        // and pppoe-only routers don't need hotspotPoolRange.
        const routerServiceType = (routerRaw as any).serviceType || 'both';
        const missingFields: string[] = [];
        if (!routerRaw.lanIp) missingFields.push("lanIp");
        if (!routerRaw.lanGateway) missingFields.push("lanGateway");
        if (!routerRaw.dns) missingFields.push("dns");
        // Only require hotspot pool when serviceType is hotspot or both
        if (routerServiceType !== 'pppoe' && !routerRaw.hotspotPoolRange)
            missingFields.push("hotspotPoolRange");
        // Only require PPPoE pool when serviceType is pppoe or both
        if (routerServiceType !== 'hotspot' && !routerRaw.pppoePoolRange)
            missingFields.push("pppoePoolRange");


        if (missingFields.length > 0) {
            return errorResponse(`Kupitisha script kumeshindwa kwa sababu router haina taarifa zifuatazo: ${missingFields.join(", ")}`, 400);
        }

        const router = decryptRouterFields(routerRaw);

        if (!router.username || !router.password) {
            return errorResponse("ROUTER_CREDENTIALS_MISSING: Router login credentials (username and password) must be set before generating a setup script.", 400);
        }

        if (isForbiddenRadiusSecret(router.radiusSecret)) {
            return errorResponse("RADIUS_SECRET_MISSING: Router has a placeholder or insecure RADIUS secret. Rotate the router RADIUS secret before generating a setup script.", 400);
        }

        const selectedLanInterfaces = parseRequestedLanInterfaces(req);

        const apiPort = router.apiPort || 80;
        const serverUrl = process.env.NEXT_PUBLIC_APP_URL || process.env.APP_URL || "";

        const cleanName = router.name.trim().replace(/^-+|-+$/g, '');
        const hotspotProfileName = `hq-hotspot-${cleanName.toLowerCase()}`;
        const hotspotServerName = `hotspot-${cleanName.toLowerCase()}`;
        const hotspotPoolName = `hs-pool-${cleanName.toLowerCase()}`;
        const pppoePoolName = `pppoe-pool-${cleanName.toLowerCase()}`;
        const lanBridgeName = 'bridge-lan';
        const dhcpNetworkCidr = deriveLanNetworkCidr(router.lanIp) || `${router.lanGateway || '192.168.88.1'}/24`;

        // Resolve VPN Subnet and VPN IP based on actual WireGuard Tunnel IP to prevent multi-tenant conflicts
        const subnetPrefix = router.wgTunnelIp ? router.wgTunnelIp.split('.').slice(0, 3).join('.') : "10.200.0";
        const vpnSubnet = `${subnetPrefix}.0/24`;
        const vpnIp = `${subnetPrefix}.1`;
        // CoA src-address restriction: only restrict to VPN IP when WireGuard is FULLY configured.
        // wgTunnelIp has a schema default of "10.200.0.1" — using it unconditionally would create
        // a broken CoA rule on non-WireGuard routers (no real tunnel = no reachable VPN IP).
        const wgFullyConfigured = !!(router.wgPrivateKey && router.wgPeerPublicKey && router.wgTunnelIp);
        const coaVpnRestriction = wgFullyConfigured ? `src-address=${vpnIp}` : "";

        // Billing portal hostname, used for the Walled Garden rule so unauthenticated
        // hotspot clients can still reach the payment/voucher page before login.
        let walledGardenHost = "";
        try {
            if (serverUrl) walledGardenHost = new URL(serverUrl).hostname;
        } catch (e) {
            logger.warn('[Script] Failed to parse APP_URL for walled garden host', {
                error: e instanceof Error ? e.message : String(e),
            });
        }


        const safeFilename = router.name
            .trim()
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '');
        return new Response(unifiedScript, {
            headers: {
                "Content-Type": "text/plain",
                "Content-Disposition": `attachment; filename="setup-${safeFilename}.rsc"`,
            },
        });

    } catch (e: any) {
        logger.error('[Script] Failed to generate router setup script', {
            error: e instanceof Error ? e.message : String(e),
        });
        return errorResponse("Failed to generate script", 500);
    }
}
