{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/name: hq-isp
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.global.tls.enabled .Values.global.tls.secretName }}
  tls:
    - hosts:
        - {{ .Values.global.domain | quote }}
      secretName: {{ .Values.global.tls.secretName | quote }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end -}}
