/**
 * RouterSetupWizard — FE-001 refactor
 *
 * Before: 1,531 lines (114 KB) — all state, logic, and JSX in one file
 * After:  ~220 lines — pure orchestrator, all JSX in sub-components:
 *
 *   WizardTypes.tsx      — shared types + WizardStepBar
 *   WizardSteps01.tsx    — Step 0 (download) + Step 1 (connection)
 *   WizardSteps23.tsx    — Step 2 (services) + Step 3 (VPN)
 *   WizardSteps456.tsx   — Step 4 (interfaces) + Step 5 (generate) + Step 6 (verify)
 */

import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import RefreshIcon from '@mui/icons-material/Refresh';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import { routersApi } from '../api';
import { getPublicApiBase } from '../utils/config';

import {
    WIZARD_STEPS, NEXT_BUTTON_LABELS,
    type EthernetInterface, type ServiceType, type VpnMode, type VerifyStatus,
} from '../components/wizard/WizardTypes';
import { Step0Download, Step1Connection } from '../components/wizard/WizardSteps01';
import { Step2Services, Step3Vpn } from '../components/wizard/WizardSteps23';
import { Step4Interfaces, Step5Generate, Step6Verify } from '../components/wizard/WizardSteps456';

const FORBIDDEN_RADIUS_SECRETS = new Set([
    'AUTOGENERATED_BY_AUTO_PUSH',
    'hqinvestment_radius_secret',
    'hqsecret',
]);

function isForbiddenRadiusSecret(value: unknown): boolean {
    return typeof value === 'string' && FORBIDDEN_RADIUS_SECRETS.has(value.trim());
}

// SEC-ROUTER-003 FIX: the wizard previously shipped with hardcoded, static
// default secrets (`hqinvestment_radius_secret`, `MyISPVpnKey2024!`) that
// were identical across every tenant/router unless an operator remembered to
// overwrite them by hand. Generate a cryptographically random secret in the
// browser instead (Web Crypto, not Math.random) so every router gets a
// unique value out of the box.
// Legacy static defaults that must never be trusted/kept if found in saved
// state or a stale draft — these are known, guessable, cross-tenant values.

interface RouterSetupWizardProps {
    router?: any;
    onClose?: () => void;
}

export default function RouterSetupWizard({ router: routerProp, onClose }: RouterSetupWizardProps = {}) {
    const { id: paramId } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const routerId = routerProp?.id || paramId;

    // ── Core state ────────────────────────────────────────────────────────
    const [currentStep, setCurrentStep] = useState(0);
    const [routerData, setRouterData] = useState<any>(routerProp || null);

    // Step 1: connection
    const [connectionStatus, setConnectionStatus] = useState<'checking' | 'online' | 'offline'>('checking');
    const [connectionError, setConnectionError] = useState<string | null>(null);

    // Step 2: services
    const [serviceType, setServiceType] = useState<ServiceType>('hotspot');
    const [pppoeLocalAddress, setPppoeLocalAddress] = useState('');
    const [pppoePoolStart, setPppoePoolStart] = useState('');
    const [pppoePoolEnd, setPppoePoolEnd] = useState('');
    const [hotspotLocalAddress, setHotspotLocalAddress] = useState('');
    const [hotspotPoolStart, setHotspotPoolStart] = useState('');
    const [hotspotPoolEnd, setHotspotPoolEnd] = useState('');
    const [radiusAddress, setRadiusAddress] = useState('');
    // SEC-ROUTER-003 FIX: no static default — generated below once (see
    // effect further down), or pulled from the router's real, already-
    // provisioned radiusSecret when available so it matches the RADIUS NAS
    // entry the backend already created for this router.
    const [radiusSecret, setRadiusSecret] = useState('');

    // Step 3: VPN
    const [vpnEnabled, setVpnEnabled] = useState(true);
    const [vpnMode, setVpnMode] = useState<VpnMode>('hybrid');

    // Step 4: interfaces
    const [interfaces, setInterfaces] = useState<EthernetInterface[]>([]);
    const [loadingInterfaces, setLoadingInterfaces] = useState(false);
    const [selectedInterfaces, setSelectedInterfaces] = useState<string[]>([]);

    // Step 5: generate
    const [configGenerated, setConfigGenerated] = useState(false);
    const [showPreview, setShowPreview] = useState(false);
    const [scriptPreview, setScriptPreview] = useState('');
    const [scriptPreviewLoading, setScriptPreviewLoading] = useState(false);
    const [scriptPreviewError, setScriptPreviewError] = useState<string | null>(null);
    const [wgConfig, setWgConfig] = useState<any>(null);
    const [actionLoading, setActionLoading] = useState(false);

    // Step 6: verify
    const [serviceVerifyStatus, setServiceVerifyStatus] = useState<VerifyStatus>('checking');
    const [vpnVerifyStatus, setVpnVerifyStatus] = useState<VerifyStatus>('checking');
    const [verifyMessage, setVerifyMessage] = useState<string>('');

    // ── Derived ───────────────────────────────────────────────────────────
    const publicApiBase = getPublicApiBase();
    const apiHost = publicApiBase.startsWith('http') ? new URL(publicApiBase).hostname : window.location.hostname;
    const routerName = routerData?.name || 'Loading...';

    // -- Initialise
    useEffect(() => {
        if (!routerData && routerId) {
            routersApi.get(routerId).then(setRouterData).catch(console.error);
        }
    }, [routerId]);


    // Fetch WireGuard config to derive suggested LAN IPs
    useEffect(() => {
        if (!routerId) return;
        routersApi.wireguard?.getConfig?.(routerId)
            .then((cfg: any) => {
                setWgConfig(cfg);
                if (!radiusAddress) setRadiusAddress(cfg?.serverTunnelIp ?? '10.0.0.1');
                if (cfg?.routerTunnelIp) {
                    const parts = cfg.routerTunnelIp.split('.');
                    const prefix = `${parts[0]}.10.${parts[2] || '0'}`;
                    const gw = `${prefix}.1`;
                    setPppoeLocalAddress(gw); setPppoePoolStart(`${prefix}.10`); setPppoePoolEnd(`${prefix}.254`);
                    setHotspotLocalAddress(gw); setHotspotPoolStart(`${prefix}.10`); setHotspotPoolEnd(`${prefix}.254`);
                }
            })
            .catch(() => { if (!radiusAddress) setRadiusAddress(apiHost); });
    }, [routerId]);

    // Per-step side-effects
    useEffect(() => {
        if (currentStep === 1) checkConnection();
        if (currentStep === 4) fetchInterfaces();
        if (currentStep === 6) runVerify();
    }, [currentStep]);

    // ── Actions ───────────────────────────────────────────────────────────
    const checkConnection = async () => {
        if (!routerId) return;
        setConnectionStatus('checking'); setConnectionError(null);
        try {
            const res = await routersApi.testConnection(routerId);
            setConnectionStatus(res.success ? 'online' : 'offline');
            if (!res.success) setConnectionError(res.message as string);
        } catch (err: any) {
            setConnectionStatus('offline');
            setConnectionError(err.message || 'Failed to connect');
        }
    };

    const fetchInterfaces = async () => {
        if (!routerId) return;
        setLoadingInterfaces(true);
        try { setInterfaces(await routersApi.listInterfaces(routerId)); }
        catch (err) { console.error('Failed to fetch interfaces:', err); }
        finally { setLoadingInterfaces(false); }
    };

    const runVerify = async () => {
        setServiceVerifyStatus('checking'); setVpnVerifyStatus('checking');
        if (!routerId) { setServiceVerifyStatus('failed'); setVpnVerifyStatus('failed'); return; }
        try {
            // RC-5 FIX: Use the new deep verification endpoint to query RouterOS state
            const verifyRes = await routersApi.verifyRouter(routerId);
            setVerifyMessage(verifyRes.statusMessage || '');

            // If the API isn't reachable at all, everything fails
            if (!verifyRes.apiReachable) {
                setServiceVerifyStatus('failed');
                setVpnVerifyStatus('failed');
                return;
            }

            // A router is considered successfully provisioned if at least one service is active
            const serviceVerified = verifyRes.hotspotConfigured || verifyRes.pppoeConfigured;
            setServiceVerifyStatus(serviceVerified ? 'success' : 'failed');

            if (vpnEnabled) {
                setVpnVerifyStatus(verifyRes.vpnActive ? 'success' : 'failed');
            } else {
                setVpnVerifyStatus('success');
            }
        } catch {
            setServiceVerifyStatus('failed');
            setVpnVerifyStatus('failed');
        }
    };


    const toggleInterface = (name: string) => setSelectedInterfaces(prev => prev.includes(name) ? prev.filter(n => n !== name) : [...prev, name]);

    // SEC-ROUTER-002 FIX (parity with backend /api/routers/[id]/script):
    // derive the VPN /24 management subnet from the WireGuard tunnel IP, so
    // Winbox/Web/API firewall rules can be scoped to it instead of the WAN.

    const getMissingServiceFields = (): string[] => {
        const missingFields: string[] = [];
        if (serviceType === 'pppoe' || serviceType === 'both') {
            if (!pppoeLocalAddress) missingFields.push('PPPoE gateway address');
            if (!pppoePoolStart) missingFields.push('PPPoE pool start');
            if (!pppoePoolEnd) missingFields.push('PPPoE pool end');
        }
        if (serviceType === 'hotspot' || serviceType === 'both') {
            if (!hotspotLocalAddress) missingFields.push('Hotspot gateway address');
            if (!hotspotPoolStart) missingFields.push('Hotspot pool start');
            if (!hotspotPoolEnd) missingFields.push('Hotspot pool end');
        }
        return missingFields;
    };

    const validateProvisionInputs = (): boolean => {
        const missingFields = getMissingServiceFields();
        if (missingFields.length > 0) {
            alert(`Missing required PPPoE/Hotspot values: ${missingFields.join(', ')}. Please fill them in before generating the script.`);
            return false;
        }

        if (isForbiddenRadiusSecret(radiusSecret) || isForbiddenRadiusSecret(routerData?.radiusSecret)) {
            alert('RADIUS_SECRET_MISSING: This router has a placeholder or insecure RADIUS secret. Update the router secret before generating or pushing configuration.');
            return false;
        }

        return true;
    };

    useEffect(() => {
        setScriptPreview('');
        setScriptPreviewError(null);
    }, [
        serviceType,
        selectedInterfaces,
        hotspotLocalAddress,
        hotspotPoolStart,
        hotspotPoolEnd,
        pppoeLocalAddress,
        pppoePoolStart,
        pppoePoolEnd,
    ]);

    // RC-1 FIX: Persist network config to DB so the script-download endpoint
    // (GET /api/routers/:id/script) can read the same values the wizard used
    // to generate the script. Previously these were only kept in React state
    // and never written back, causing "missing metadata" errors.
    const persistNetworkConfig = async (): Promise<boolean> => {
        if (!routerId) return false;
        try {
            const lanGw = serviceType !== 'pppoe' ? hotspotLocalAddress : pppoeLocalAddress;
            const payload: Record<string, string | null> = {
                lanIp: lanGw ? `${lanGw}/24` : null,
                lanGateway: lanGw || null,
                dns: (routerData?.dns as string) || '8.8.8.8,8.8.4.4',
                serviceType,
                // Only persist pool ranges that are relevant to the chosen serviceType
                hotspotPoolRange: serviceType !== 'pppoe'
                    ? (hotspotPoolStart && hotspotPoolEnd ? `${hotspotPoolStart}-${hotspotPoolEnd}` : null)
                    : null,
                pppoePoolRange: serviceType !== 'hotspot'
                    ? (pppoePoolStart && pppoePoolEnd ? `${pppoePoolStart}-${pppoePoolEnd}` : null)
                    : null,
            };
            await routersApi.update(routerId, payload);
            return true;
        } catch (err) {
            console.error('[Wizard] Failed to persist network config to DB:', err);
            return false;
        }
    };

    const handlePreviewConfig = async () => {
        if (!routerId) return;

        if (showPreview) {
            setShowPreview(false);
            return;
        }

        if (!validateProvisionInputs()) return;

        setShowPreview(true);
        setScriptPreviewLoading(true);
        setScriptPreviewError(null);
        setScriptPreview('');
        try {
            const persisted = await persistNetworkConfig();
            if (!persisted) throw new Error('Failed to save router network settings before preview.');

            const script = await routersApi.getScript(routerId, selectedInterfaces);
            if (script.includes('AUTOGENERATED_BY_AUTO_PUSH')) {
                throw new Error('RADIUS_SECRET_MISSING: Server generated a script with a forbidden placeholder secret.');
            }
            setScriptPreview(script);
        } catch (err: any) {
            setScriptPreviewError(err.message || String(err));
        } finally {
            setScriptPreviewLoading(false);
        }
    };

    const getGeneratedScript = (): string => {
        if (scriptPreviewLoading) return 'Loading server-generated script preview...';
        if (scriptPreviewError) return `Failed to load script preview: ${scriptPreviewError}`;
        return scriptPreview || 'Click Preview Script to load the server-generated configuration.';
    };

    const handleDownloadConfig = async () => {
        if (!routerId) return;
        if (!validateProvisionInputs()) return;

        setActionLoading(true);
        try {
            // RC-1 FIX: Persist config to DB first so the backend script-download
            // endpoint has the same values the wizard used to generate this file.
            const persisted = await persistNetworkConfig();
            if (!persisted) throw new Error('Failed to save router network settings before download.');

            await routersApi.downloadScript(routerId, routerName, selectedInterfaces);
            setConfigGenerated(true);
        } catch (err: any) {
            alert('Failed to download script: ' + (err.message || String(err)));
        } finally {
            setActionLoading(false);
        }
    };

    const handleAutoPush = async () => {
        if (!routerId) return;
        if (!validateProvisionInputs()) return;

        setActionLoading(true);
        try {
            const persisted = await persistNetworkConfig();
            if (!persisted) throw new Error('Failed to save router network settings before Auto-Push.');

            const res = await routersApi.wireguard.pushConfig(routerId, selectedInterfaces);
            if (res.jobId) {
                // Poll for job completion
                let jobStatus = 'waiting';
                let attempt = 0;
                while ((jobStatus === 'waiting' || jobStatus === 'active') && attempt < 60) {
                    await new Promise(r => setTimeout(r, 2000)); // poll every 2s
                    try {
                        const pollRes = await routersApi.wireguard.getJobStatus(routerId, res.jobId as string);

                        jobStatus = pollRes.status;
                        if (jobStatus === 'completed') {
                            setConfigGenerated(true);
                            alert(pollRes.message || 'Configuration pushed successfully.');
                            handleNext();
                            return;
                        } else if (jobStatus === 'failed') {
                            alert('Auto-Push Failed: ' + (pollRes.error || 'Unknown error'));
                            return;
                        }
                    } catch (pollErr: any) {
                        const errMsg = pollErr.message || String(pollErr);
                        if (errMsg.includes('AUTO_PUSH_API_NON_JSON_RESPONSE')) {
                            alert(`AUTO_PUSH_API_NON_JSON_RESPONSE\nThe backend returned an invalid (HTML or empty) response while checking job status. This usually means a gateway timeout or proxy error occurred.\nDetails: ${errMsg}\nJob ID: ${res.jobId}`);
                            return;
                        }
                        // For other network/transient errors, keep retrying up to 60 attempts
                        console.warn('Poll attempt failed:', errMsg);
                    }
                    attempt++;
                }
                if (attempt >= 60) alert('Auto-Push is taking too long. Please check status later.');
            } else if (res.success || res.partialSuccess) {
                setConfigGenerated(true);
                alert(res.message || 'Configuration pushed successfully.');
                handleNext();
            } else {
                alert('Auto-Push Failed: ' + (res.message || 'Unknown error'));
            }
        } catch (err: any) {
            alert('Auto-Push Failed: ' + (err.message || String(err)));
        } finally {
            setActionLoading(false);
        }
    };

    const handleNext = () => {
        if (currentStep === 1 && connectionStatus !== 'online') { alert('Please wait for connection check or ensure router is online.'); return; }
        if (currentStep === 4 && selectedInterfaces.length === 0) { alert('Please select at least one interface for the service bridge.'); return; }
        if (currentStep === 5 && !configGenerated) { if (!window.confirm('You have not generated the RSC config yet. Continue anyway?')) return; }
        if (currentStep < WIZARD_STEPS.length - 1) {
            setCurrentStep(currentStep + 1);
        } else {
            if (onClose) onClose(); else navigate('/routers');
        }
    };
    const handlePrev = () => { if (currentStep > 0) setCurrentStep(currentStep - 1); };
    const handleFinish = () => { if (onClose) onClose(); else navigate('/routers'); };

    // ── Step switcher ─────────────────────────────────────────────────────
    const renderStep = () => {
        switch (currentStep) {
            case 0: return <Step0Download routerName={routerName} wgConfig={wgConfig} />;
            case 1: return <Step1Connection connectionStatus={connectionStatus} connectionError={connectionError} routerData={routerData} onRetry={checkConnection} onNext={handleNext} onBack={() => setCurrentStep(0)} />;
            case 2: return <Step2Services serviceType={serviceType} setServiceType={setServiceType} pppoeLocalAddress={pppoeLocalAddress} setPppoeLocalAddress={setPppoeLocalAddress} pppoePoolStart={pppoePoolStart} setPppoePoolStart={setPppoePoolStart} pppoePoolEnd={pppoePoolEnd} setPppoePoolEnd={setPppoePoolEnd} hotspotLocalAddress={hotspotLocalAddress} setHotspotLocalAddress={setHotspotLocalAddress} hotspotPoolStart={hotspotPoolStart} setHotspotPoolStart={setHotspotPoolStart} hotspotPoolEnd={hotspotPoolEnd} setHotspotPoolEnd={setHotspotPoolEnd} radiusAddress={radiusAddress} setRadiusAddress={setRadiusAddress} radiusSecret={radiusSecret} setRadiusSecret={setRadiusSecret} />;
            case 3: return <Step3Vpn vpnEnabled={vpnEnabled} setVpnEnabled={setVpnEnabled} vpnMode={vpnMode} setVpnMode={setVpnMode} />;
            case 4: return <Step4Interfaces routerName={routerName} interfaces={interfaces} loadingInterfaces={loadingInterfaces} selectedInterfaces={selectedInterfaces} onToggleInterface={toggleInterface} onRefresh={fetchInterfaces} />;
            case 5:
                return <Step5Generate routerName={routerName} serviceType={serviceType} selectedInterfaces={selectedInterfaces} vpnEnabled={vpnEnabled} hotspotLocalAddress={hotspotLocalAddress} pppoeLocalAddress={pppoeLocalAddress} configGenerated={configGenerated} showPreview={showPreview} getGeneratedScript={getGeneratedScript} onPreview={handlePreviewConfig} onDownload={handleDownloadConfig} onAutoPush={handleAutoPush} actionLoading={actionLoading} />;
            case 6: return <Step6Verify routerName={routerName} serviceType={serviceType} vpnEnabled={vpnEnabled} vpnMode={vpnMode} serviceVerifyStatus={serviceVerifyStatus} vpnVerifyStatus={vpnVerifyStatus} verifyMessage={verifyMessage} onGoBack={() => setCurrentStep(0)} onFinish={handleFinish} />;
            default: return null;
        }
    };

    // ── Render ────────────────────────────────────────────────────────────
    return (
        <div style={{ maxWidth: 900, margin: '0 auto', paddingBottom: 80 }}>
            {/* Header */}
            <div style={{ marginBottom: 4 }}>
                <h1 style={{ fontSize: '1.4rem', fontWeight: 700, marginBottom: 2 }}>Router Setup Wizard</h1>
                <p style={{ color: '#0d9488', fontSize: '0.9rem' }}>{routerName}</p>
            </div>

            {/* Step bar */}
            <div style={{ overflowX: 'auto', width: '100%' }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '24px 0', margin: '0 auto', maxWidth: 800 }}>
                    {WIZARD_STEPS.map((step, i) => (
                        <div key={i} style={{ display: 'flex', alignItems: 'center', flex: i < WIZARD_STEPS.length - 1 ? 1 : 0 }}>
                            <div style={{ textAlign: 'center', minWidth: 60 }}>
                                <div style={{ width: 36, height: 36, borderRadius: '50%', margin: '0 auto 4px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: i < currentStep ? '#16a34a' : i === currentStep ? (i === 3 ? '#7c3aed' : '#16a34a') : '#e5e7eb', color: i <= currentStep ? '#fff' : '#9ca3af', fontWeight: 600, fontSize: '0.85rem', transition: 'all 0.3s' }}>
                                    {i < currentStep ? <CheckCircleIcon style={{ fontSize: 18 }} /> : <span style={{ fontSize: 18, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>{step.icon}</span>}
                                </div>
                                <div style={{ fontSize: '0.7rem', fontWeight: i === currentStep ? 700 : 400, color: i <= currentStep ? (i === 3 && i === currentStep ? '#7c3aed' : '#16a34a') : '#9ca3af' }}>{step.label}</div>
                                <div style={{ fontSize: '0.6rem', color: i <= currentStep ? (i === 3 && i === currentStep ? '#7c3aed' : '#16a34a') : '#9ca3af' }}>{step.sub}</div>
                            </div>
                            {i < WIZARD_STEPS.length - 1 && (
                                <div style={{ flex: 1, height: 2, margin: '0 4px', background: i < currentStep ? '#16a34a' : '#e5e7eb', transition: 'all 0.3s', marginBottom: 24 }} />
                            )}
                        </div>
                    ))}
                </div>
            </div>

            {/* Step content */}
            <div style={{ paddingBottom: 16 }}>{renderStep()}</div>

            {/* Fixed nav bar */}
            <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '12px', padding: '12px 24px', borderTop: '1px solid var(--border-light)', background: 'var(--bg-primary, #fff)', zIndex: 100, boxShadow: '0 -2px 8px rgba(0,0,0,0.08)' }}>
                <div style={{ display: 'flex', alignItems: 'center', minWidth: 120 }}>
                    {currentStep > 0 && (
                        <button className="btn btn-secondary" onClick={handlePrev} style={{ minWidth: 140, justifyContent: 'center' }}>
                            <ArrowBackIcon fontSize="small" /> Previous
                        </button>
                    )}
                </div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', minWidth: 220 }}>
                    {currentStep === 6 && (serviceVerifyStatus === 'failed' || serviceVerifyStatus === 'checking') ? (
                        <button className="btn" style={{ background: '#f3f4f6', color: '#374151', fontWeight: 600, border: '1px solid var(--border)', minWidth: 170, justifyContent: 'center' }} onClick={runVerify}>
                            <RefreshIcon fontSize="small" /> {serviceVerifyStatus === 'checking' ? 'Checking...' : 'Recheck Status'}
                        </button>
                    ) : (
                        <button className="btn" style={{ background: currentStep === 3 ? '#7c3aed' : '#16a34a', color: '#fff', fontWeight: 600, minWidth: 220, justifyContent: 'center' }} onClick={handleNext}>
                            {NEXT_BUTTON_LABELS[currentStep] ?? 'Next'} <ArrowForwardIcon fontSize="small" />
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
}
