/**
 * Canonical RouterOS RSC Generator — HQ INVESTMENT ISP Billing System
 *
 * ARCHITECTURE:
 *   This is the single canonical source of truth for the RouterOS setup script.
 *   Download Script (non-legacy), Script Preview, and Auto-Push MUST all use this
 *   generator for the desired-state model. Auto-Push executes phases programmatically
 *   via the REST API, but must produce the same configuration as this generator.
 *
 * DEFECT FIXES (see implementation_plan.md):
 *   1+2+5  $targetBridge never referenced unless a LAN bridge is declared.
 *          Hotspot/PPPoE/DHCP/Walled-Garden all gated on hasBridgeInterfaces.
 *   3      WAN interface discovered from the active default route at runtime.
 *          "ether1" is only the last-resort fallback with an explicit log warning.
 *   4      DROP WAN input moved to PHASE 9 — emitted ONLY when wg-hq exists.
 *   8      /system identity set name= emitted as first executable line.
 */

export type RouterServiceType = 'pppoe' | 'hotspot' | 'both';

export interface RouterSetupWizardScriptParams {
  routerName: string;
  routerId: string;
  publicApiBase: string;
  apiHost: string;
  serviceType: RouterServiceType;
  selectedInterfaces: string[];
  vpnEnabled: boolean;
  vpnProtocol?: string;
  vpnPoolStart?: string;
  vpnPoolEnd?: string;
  vpnSecrets?: Array<{
    username: string;
    password: string;
    protocol?: string;
    profile?: string;
    localAddress?: string;
    remoteAddress?: string;
  }>;
  hotspotLocalAddress: string;
  hotspotPoolStart: string;
  hotspotPoolEnd: string;
  pppoeLocalAddress: string;
  pppoePoolStart: string;
  pppoePoolEnd: string;
  radiusAddress: string;
  radiusSecret: string;
  vpnMode?: string;
  vpnDns?: string;
  ipsecSecret?: string;
  wgConfig?: {
    routerTunnelIp?: string | null;
    serverTunnelIp?: string | null;
    privateKey?: string | null;
    peerPublicKey?: string | null;
    serverEndpoint?: string | null;
    listenPort?: number | null;
  } | null;
  certName?: string;
  vpnManagementSubnet?: string | null;
  dnsServers?: string;
}

export interface RouterSetupWizardServiceValidation {
  ok: boolean;
  missingFields: string[];
}

export interface RouterSetupWizardScriptValidation {
  ok: boolean;
  errors: string[];
}

/** Placeholder values that must never reach a production RouterOS device. */
const FORBIDDEN_RADIUS_SECRETS_WIZARD = new Set([
  'AUTOGENERATED_BY_AUTO_PUSH',
  'hqinvestment_radius_secret',
  'hqsecret',
  '',
]);

export function sanitizeMikroTikName(name: string): string {
  if (!name) return 'unnamed';
  return (
    name
      .trim()
      .replace(/\s+/g, '-')
      .replace(/[^a-zA-Z0-9-]/g, '')
      .replace(/-+/g, '-')
      .replace(/^-+|-+$/g, '')
      .toLowerCase() || 'unnamed'
  );
}

/** Escape a value for embedding inside a RouterOS double-quoted string. */
function escapeMikroTikString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function normalizeInterfaceList(selectedInterfaces: string[] = []): string[] {
  const seen = new Set<string>();
  const normalized: string[] = [];
  for (const value of selectedInterfaces) {
    if (!value) continue;
    const item = value.trim();
    if (!item || seen.has(item)) continue;
    seen.add(item);
    normalized.push(item);
  }
  return normalized;
}

export function normalizeWizardScriptInputs(
  input: Partial<RouterSetupWizardScriptParams>,
): RouterSetupWizardScriptParams {
  return {
    routerName: input.routerName || 'Router',
    routerId: input.routerId || 'router',
    publicApiBase: input.publicApiBase || '',
    apiHost: input.apiHost || 'router.local',
    serviceType: input.serviceType || 'hotspot',
    selectedInterfaces: normalizeInterfaceList(input.selectedInterfaces),
    vpnEnabled: input.vpnEnabled ?? true,
    vpnMode: input.vpnMode,
    vpnProtocol: input.vpnProtocol,
    vpnPoolStart: input.vpnPoolStart,
    vpnPoolEnd: input.vpnPoolEnd,
    vpnSecrets: input.vpnSecrets || [],
    hotspotLocalAddress: input.hotspotLocalAddress || '',
    hotspotPoolStart: input.hotspotPoolStart || '',
    hotspotPoolEnd: input.hotspotPoolEnd || '',
    pppoeLocalAddress: input.pppoeLocalAddress || '',
    pppoePoolStart: input.pppoePoolStart || '',
    pppoePoolEnd: input.pppoePoolEnd || '',
    radiusAddress: input.radiusAddress || '',
    radiusSecret: input.radiusSecret || '',
    vpnDns: input.vpnDns,
    ipsecSecret: input.ipsecSecret,
    wgConfig: input.wgConfig || null,
    certName: input.certName || 'hq-hotspot-cert',
    vpnManagementSubnet: input.vpnManagementSubnet || null,
    dnsServers: input.dnsServers || '8.8.8.8,8.8.4.4',
  };
}

export function validateRouterSetupWizardServiceInputs(input: {
  serviceType: RouterSetupWizardScriptParams['serviceType'];
  hotspotLocalAddress: string;
  pppoeLocalAddress: string;
  hotspotPoolStart: string;
  hotspotPoolEnd: string;
  pppoePoolStart: string;
  pppoePoolEnd: string;
}): RouterSetupWizardServiceValidation {
  const missingFields: string[] = [];
  if (input.serviceType === 'pppoe' || input.serviceType === 'both') {
    if (!input.pppoeLocalAddress.trim()) missingFields.push('PPPoE gateway address');
    if (!input.pppoePoolStart.trim()) missingFields.push('PPPoE pool start');
    if (!input.pppoePoolEnd.trim()) missingFields.push('PPPoE pool end');
  }
  if (input.serviceType === 'hotspot' || input.serviceType === 'both') {
    if (!input.hotspotLocalAddress.trim()) missingFields.push('Hotspot gateway address');
    if (!input.hotspotPoolStart.trim()) missingFields.push('Hotspot pool start');
    if (!input.hotspotPoolEnd.trim()) missingFields.push('Hotspot pool end');
  }
  return { ok: missingFields.length === 0, missingFields };
}

/**
 * Pre-generation validation gate.
 *
 * MUST be called before buildRouterWizardScript(). If this returns ok=false,
 * generation MUST NOT proceed. The generator itself does not call this
 * automatically so that callers can surface errors to the UI before generating.
 */
export function validateWizardScriptParams(
  params: RouterSetupWizardScriptParams,
): RouterSetupWizardScriptValidation {
  const errors: string[] = [];

  if (!params.routerName || !params.routerName.trim()) {
    errors.push('ROUTER_NAME_MISSING: routerName is required');
  }
  if (!params.radiusAddress || !params.radiusAddress.trim()) {
    errors.push('RADIUS_ADDRESS_MISSING: radiusAddress is required');
  }
  if (!params.radiusSecret || FORBIDDEN_RADIUS_SECRETS_WIZARD.has(params.radiusSecret.trim())) {
    errors.push(
      'RADIUS_SECRET_MISSING: radiusSecret is missing or uses a forbidden placeholder value',
    );
  }

  // Service-specific field validation
  const svcValidation = validateRouterSetupWizardServiceInputs(params);
  if (!svcValidation.ok) {
    errors.push(...svcValidation.missingFields.map((f) => `SERVICE_FIELD_MISSING: ${f}`));
  }

  return { ok: errors.length === 0, errors };
}

/**
 * Build the hotspot unauthenticated-forward drop rule lines.
 *
 * DEFECT-5 FIX: This function must only be called with a concrete bridge name
 * variable reference ($targetBridge) that is GUARANTEED to be declared in scope.
 * Never call this when selectedInterfaces.length === 0.
 */
export function buildHotspotFlowEnforcementLines(targetBridge: string): string[] {
  return [
    '',
    '# ===== Hotspot flow enforcement =====',
    '# CRITICAL: this drop rule must come AFTER walled-garden rules so unauthenticated',
    '# clients can still reach the billing portal login page.',
    ':if ([:len [/ip firewall filter find where comment="Drop unauthenticated LAN forward - HQ INVESTMENT"]] = 0) do={',
    `    /ip firewall filter add chain=forward in-interface=${targetBridge} action=drop comment="Drop unauthenticated LAN forward - HQ INVESTMENT"`,
    '}',
  ];
}

export function buildRouterWizardScript(params: RouterSetupWizardScriptParams): string {
  const normalized = normalizeWizardScriptInputs(params);
  const safeRouterName = sanitizeMikroTikName(normalized.routerName);
  const escapedRouterName = escapeMikroTikString(normalized.routerName);

  const hsPoolName = `hs-pool-${safeRouterName}`;
  const pppoePoolName = `pppoe-pool-${safeRouterName}`;
  const pppoeProfile = `pppoe-profile-${safeRouterName}`;
  const hotspotProfile = `hq-hotspot-${safeRouterName}`;
  const vpnPoolName = `vpn-pool-${safeRouterName}`;
  const vpnProfile = `vpn-profile-${safeRouterName}`;
  const targetBridge = `bridge-${safeRouterName}`;
  const dnsServers = normalized.dnsServers || '8.8.8.8,8.8.4.4';

  const hotspotPrefix = normalized.hotspotLocalAddress
    ? normalized.hotspotLocalAddress.split('.').slice(0, 3).join('.')
    : '';
  const hotspotNetwork = hotspotPrefix ? `${hotspotPrefix}.0/24` : '';
  const hotspotCidr = normalized.hotspotLocalAddress
    ? `${normalized.hotspotLocalAddress}/24`
    : '';

  /**
   * DEFECT-1+2+5 FIX:
   * $targetBridge is ONLY declared when hasBridgeInterfaces === true.
   * Every section that emits `$targetBridge` is guarded by this flag.
   * When false, those sections emit BLOCKED_BY_DEPENDENCY comments instead.
   */
  const hasBridgeInterfaces = normalized.selectedInterfaces.length > 0;
  const vpnCableSubnet =
    normalized.vpnManagementSubnet ||
    (normalized.wgConfig?.serverTunnelIp
      ? `${normalized.wgConfig.serverTunnelIp.split('.').slice(0, 3).join('.')}.0/24`
      : normalized.wgConfig?.routerTunnelIp
        ? `${normalized.wgConfig.routerTunnelIp.split('.').slice(0, 3).join('.')}.0/24`
        : '');

  const lines: string[] = [
    // ── Header ──────────────────────────────────────────────────────────────
    '# HQ INVESTMENT Router Setup Wizard - generated configuration',
    `# Router:     ${normalized.routerName}`,
    `# Router ID:  ${normalized.routerId}`,
    `# Generated:  ${new Date().toISOString()}`,
    '#',
    '# SECURITY WARNING: This script may contain sensitive credentials.',
    '# Run via a LOCAL/CONSOLE connection. Delete this file immediately after use.',
    '',

    // ── PHASE 1: Identity ────────────────────────────────────────────────────
    '# ===== PHASE 1: RouterOS Identity =====',
    '# DEFECT-8 FIX: Always set identity from Router.name, never Router.username.',
    `/system identity set name="${escapedRouterName}"`,
    '',

    // ── PHASE 1b: Management Safety ──────────────────────────────────────────
    '# ===== PHASE 1b: Management Safety (Interface Lists & MAC Server) =====',
    ':if ([:len [/interface list find name="hq-mgmt"]] = 0) do={',
    '    /interface list add name="hq-mgmt" comment="HQ INVESTMENT management interfaces (VPN only)"',
    '}',
    ':if ([:len [/interface list find name="LAN"]] = 0) do={',
    '    /interface list add name="LAN" comment="HQ INVESTMENT LAN"',
    '}',
    '# Only add wg-hq to hq-mgmt if the interface already exists on the router.',
    ':if ([:len [/interface wireguard find name="wg-hq"]] > 0) do={',
    '    :if ([:len [/interface list member find list="hq-mgmt" interface="wg-hq"]] = 0) do={',
    '        /interface list member add list="hq-mgmt" interface="wg-hq"',
    '    }',
    '}',
    '# Protect MAC Server & Discovery by restricting to LAN (prevents WAN L2 exposure)',
    '# Using LAN preserves the factory-default behavior so local physical ports remain accessible.',
    '/tool mac-server set allowed-interface-list=LAN',
    '/tool mac-server mac-winbox set allowed-interface-list=LAN',
    '/ip neighbor discovery-settings set discover-interface-list=LAN',
    '',

    // ── PHASE 3: Semantic WAN Discovery ──────────────────────────────────────
    '# ===== PHASE 3: Semantic WAN Interface Discovery =====',
    '# DEFECT-3 FIX: WAN interface is discovered from the active default route.',
    '# "ether1" is only a last-resort fallback. A log warning fires if used.',
    ':local wanIface ""',
    ':foreach r in=[/ip route find dst-address="0.0.0.0/0" active=yes] do={',
    '    :if ($wanIface = "") do={',
    '        :set wanIface [/ip route get $r vrf-interface]',
    '    }',
    '}',
    ':if ($wanIface = "") do={',
    '    /log warning "HQ INVESTMENT: No active default route found. Falling back to ether1 for WAN. Verify this is correct for your hardware."',
    '    :set wanIface "ether1"',
    '}',
    '/log info "HQ INVESTMENT: WAN interface identified as $wanIface"',
    ':if ([:len [/interface list find name="WAN"]] = 0) do={',
    '    /interface list add name="WAN" comment="HQ INVESTMENT WAN"',
    '}',
    ':if ([:len [/interface list member find list="WAN" interface=$wanIface]] = 0) do={',
    '    /interface list member add list="WAN" interface=$wanIface comment="HQ INVESTMENT WAN port"',
    '}',
    '',

    // ── REST API Services (HTTP + conditional HTTPS) ──────────────────────────
    '# ===== REST API Services Configuration =====',
    '# DEFECT-12 FIX: www (HTTP) is ALWAYS enabled for REST API fallback.',
    '# www-ssl (HTTPS) is ONLY enabled when a valid, non-expired certificate exists.',
    '# The application will use HTTPS if available, HTTP if certificate is missing.',
    '/ip service set www disabled=no port=80',
    '/log info "HQ INVESTMENT: www (HTTP) enabled on port 80"',
    '',
    '# Check for valid certificate and enable www-ssl only if found',
    ':local certCount [:len [/certificate find where name!="none" expires-after!="0s"]]',
    ':if ($certCount > 0) do={',
    '    :local certName [/certificate get [find where name!="none" expires-after!="0s"] name]',
    '    /ip service set www-ssl disabled=no port=443 certificate=$certName',
    '    /log info "HQ INVESTMENT: www-ssl (HTTPS) enabled on port 443 with certificate $certName"',
    '} else={',
    '    /ip service set www-ssl disabled=yes',
    '    /log warning "HQ INVESTMENT: No valid certificate found. www-ssl disabled. HTTP (port 80) is available for management."',
    '}',
    '',

    // ── PHASE 1c: Firewall ACCEPT rules (management — NO DROP yet) ───────────
    '# ===== PHASE 1c: Firewall ACCEPT Rules =====',
    '# DEFECT-4 FIX: DROP WAN is NOT applied here.',
    '# It is deferred to PHASE 9 and is conditional on wg-hq existing and verified.',
    '# ===== Basic Stateful Firewall Rules =====',
    ':if ([:len [/ip firewall filter find where comment="HQ: accept established input"]] = 0) do={',
    '    /ip firewall filter add chain=input action=accept connection-state=established,related,untracked comment="HQ: accept established input"',
    '}',
    ':if ([:len [/ip firewall filter find where comment="HQ: drop invalid input"]] = 0) do={',
    '    /ip firewall filter add chain=input action=drop connection-state=invalid comment="HQ: drop invalid input"',
    '}',
    ':if ([:len [/ip firewall filter find where comment="HQ: accept ICMP"]] = 0) do={',
    '    /ip firewall filter add chain=input action=accept protocol=icmp comment="HQ: accept ICMP"',
    '}',
    ':if ([:len [/ip firewall filter find where comment="HQ: fasttrack forward"]] = 0) do={',
    '    /ip firewall filter add chain=forward action=fasttrack-connection connection-state=established,related comment="HQ: fasttrack forward"',
    '}',
    ':if ([:len [/ip firewall filter find where comment="HQ: accept established forward"]] = 0) do={',
    '    /ip firewall filter add chain=forward action=accept connection-state=established,related,untracked comment="HQ: accept established forward"',
    '}',
    ':if ([:len [/ip firewall filter find where comment="HQ: drop invalid forward"]] = 0) do={',
    '    /ip firewall filter add chain=forward action=drop connection-state=invalid comment="HQ: drop invalid forward"',
    '}',
    ...(normalized.vpnManagementSubnet
      ? [
        ':if ([:len [/ip firewall filter find where comment="Allow HQ INVESTMENT API Access (VPN only)"]] = 0) do={',
        `    /ip firewall filter add chain=input action=accept protocol=tcp dst-port=80,443,8291 in-interface-list=hq-mgmt src-address=${normalized.vpnManagementSubnet} comment="Allow HQ INVESTMENT API Access (VPN only)"`,
        '}',
      ]
      : [
        '# vpnManagementSubnet not set — skipping VPN-source accept rule.',
        '# Configure WireGuard and re-generate to add the VPN-only management accept.',
      ]),
    '',

    // ── PHASE 4: Bridge Setup ─────────────────────────────────────────────────
    '# ===== PHASE 4: LAN Bridge =====',
    ...(hasBridgeInterfaces
      ? [
        // DEFECT-1 FIX: :local targetBridge declared ONLY in this branch.
        `:local targetBridge "${targetBridge}"`,
        `:if ([:len [/interface bridge find where name=$targetBridge]] = 0) do={ /interface bridge add name=$targetBridge protocol-mode=none arp=enabled vlan-filtering=no comment="HQ Investment Bridge" }`,
        `:if ([:len [/interface bridge find where name=$targetBridge]] > 0) do={ /interface bridge set [find name=$targetBridge] protocol-mode=none arp=enabled vlan-filtering=no }`,
        ...normalized.selectedInterfaces.map(
          (iface) =>
            `:if ([:len [/interface bridge port find where interface="${iface}"]] = 0) do={ /interface bridge port add bridge=$targetBridge interface=${iface} comment="HQ LAN port" }`,
        ),
        // Add both the bridge and each selected physical interface to LAN / hq-mgmt.
        // This preserves local MAC WinBox access after reboot when the router is physically
        // connected on the LAN ports before the bridge has re-established itself.
        `:if ([:len [/interface list find name="LAN"]] = 0) do={ /interface list add name="LAN" comment="HQ INVESTMENT LAN" }`,
        ...normalized.selectedInterfaces.map(
          (iface) =>
            `:if ([:len [/interface list member find list="LAN" interface="${iface}"]] = 0) do={ /interface list member add list="LAN" interface="${iface}" comment="HQ LAN port" }`,
        ),
        ...normalized.selectedInterfaces.map(
          (iface) =>
            `:if ([:len [/interface list member find list="hq-mgmt" interface="${iface}"]] = 0) do={ /interface list member add list="hq-mgmt" interface="${iface}" comment="HQ Mgmt port" }`,
        ),
        `:if ([:len [/interface list member find list="LAN" interface="${targetBridge}"]] = 0) do={ /interface list member add list="LAN" interface="${targetBridge}" comment="HQ LAN bridge" }`,
        `:if ([:len [/interface list member find list="hq-mgmt" interface="${targetBridge}"]] = 0) do={ /interface list member add list="hq-mgmt" interface="${targetBridge}" comment="HQ Mgmt bridge" }`,
      ]
      : [
        // DEFECT-1 FIX: No targetBridge variable is declared — no variable will be referenced.
        '# BLOCKED_BY_DEPENDENCY: No LAN interfaces were selected.',
        '# Bridge creation is skipped. The targetBridge variable is NOT declared in this script.',
        '# Hotspot, PPPoE, DHCP, RADIUS, and Walled Garden sections are omitted below.',
        '# Select at least one LAN interface in the Router Setup Wizard and re-generate.',
      ]),
    '',

    // ── PHASE 5+7: Hotspot / PPPoE / DHCP — gated on hasBridgeInterfaces ─────
    '# ===== PHASE 5+7: LAN IP, Hotspot / PPPoE / DHCP Services =====',
    `# Service type: ${normalized.serviceType}`,
    '',
    ...(hasBridgeInterfaces
      ? [
        ...((normalized.hotspotLocalAddress || normalized.pppoeLocalAddress)
          ? [
            '# ===== LAN IP Address =====',
            `:local lanCidr "${normalized.hotspotLocalAddress || normalized.pppoeLocalAddress}/24"`,
            `:if ([:len [/ip address find where address=$lanCidr interface=$targetBridge]] = 0) do={ /ip address add address=$lanCidr interface=$targetBridge comment="HQ INVESTMENT LAN" }`,
          ]
          : []),
        // PPPoE server
        ...(normalized.serviceType === 'pppoe' || normalized.serviceType === 'both'
          ? [
            '# ===== PPPoE Server =====',
            `:if ([:len [/ip pool find where name="${pppoePoolName}"]] = 0) do={ /ip pool add name="${pppoePoolName}" ranges=${normalized.pppoePoolStart}-${normalized.pppoePoolEnd} }`,
            `:if ([:len [/ppp profile find where name="${pppoeProfile}"]] = 0) do={ /ppp profile add name="${pppoeProfile}" local-address=${normalized.pppoeLocalAddress} remote-address="${pppoePoolName}" dns-server=${dnsServers} use-compression=no use-encryption=yes } else={ /ppp profile set [find where name="${pppoeProfile}"] local-address=${normalized.pppoeLocalAddress} remote-address="${pppoePoolName}" dns-server=${dnsServers} use-compression=no use-encryption=yes }`,
            `:if ([:len [/interface pppoe-server server find where service-name="hq-pppoe-${safeRouterName}"]] = 0) do={ /interface pppoe-server server add service-name="hq-pppoe-${safeRouterName}" interface=$targetBridge default-profile="${pppoeProfile}" authentication=chap,mschap1,mschap2 one-session-per-host=yes disabled=no } else={ /interface pppoe-server server set [find where service-name="hq-pppoe-${safeRouterName}"] interface=$targetBridge default-profile="${pppoeProfile}" authentication=chap,mschap1,mschap2 one-session-per-host=yes disabled=no }`,
            ':if ([:len [/ip firewall filter find where comment="Allow PPPoE to Internet"]] = 0) do={',
            '    /ip firewall filter add chain=forward in-interface=all-ppp out-interface-list=WAN action=accept comment="Allow PPPoE to Internet"',
            '}',
          ]
          : []),
        // Hotspot server
        ...(normalized.serviceType === 'hotspot' || normalized.serviceType === 'both'
          ? [
            '',
            '# ===== Hotspot Server =====',
            `:if ([:len [/ip pool find where name="${hsPoolName}"]] = 0) do={ /ip pool add name="${hsPoolName}" ranges=${normalized.hotspotPoolStart}-${normalized.hotspotPoolEnd} }`,
            `:if ([:len [/ip hotspot profile find where name="${hotspotProfile}"]] = 0) do={ /ip hotspot profile add name="${hotspotProfile}" hotspot-address=${normalized.hotspotLocalAddress} html-directory=hotspot login-by=http-chap,https,cookie use-radius=yes }`,
            `:if ([:len [/ip hotspot find where name="hq-hotspot-${safeRouterName}"]] = 0) do={ /ip hotspot add name="hq-hotspot-${safeRouterName}" interface=$targetBridge address-pool="${hsPoolName}" profile="${hotspotProfile}" disabled=no } else={ /ip hotspot set [find name="hq-hotspot-${safeRouterName}"] interface=$targetBridge address-pool="${hsPoolName}" profile="${hotspotProfile}" disabled=no }`,
            ...(hotspotNetwork
              ? [
                `:if ([:len [/ip dhcp-server network find where address="${hotspotNetwork}"]] = 0) do={ /ip dhcp-server network add address=${hotspotNetwork} gateway=${normalized.hotspotLocalAddress} dns-server=${dnsServers} } else={ /ip dhcp-server network set [find where address="${hotspotNetwork}"] gateway=${normalized.hotspotLocalAddress} dns-server=${dnsServers} }`,
              ]
              : []),
            `:if ([:len [/ip dhcp-server find where name="dhcp-${safeRouterName}"]] = 0) do={ /ip dhcp-server add name="dhcp-${safeRouterName}" interface=$targetBridge address-pool="${hsPoolName}" lease-time=1h disabled=no } else={ /ip dhcp-server set [find where name="dhcp-${safeRouterName}"] interface=$targetBridge address-pool="${hsPoolName}" lease-time=1h disabled=no }`,
          ]
          : []),
      ]
      : [
        // DEFECT-2 FIX: No $targetBridge reference emitted here.
        '# BLOCKED_BY_DEPENDENCY: Hotspot/PPPoE/DHCP skipped — no bridge configured.',
      ]),
    '',
    '# ===== NAT Masquerade =====',
    ':if ([:len [/ip firewall nat find where comment="HQ INVESTMENT NAT"]] = 0) do={',
    '    /ip firewall nat add chain=srcnat action=masquerade out-interface-list=WAN comment="HQ INVESTMENT NAT"',
    '}',
    '',
    // ── WireGuard VPN (HQ INVESTMENT) ─────────────────────────────────────────
    ...(normalized.wgConfig?.privateKey && normalized.wgConfig?.peerPublicKey && normalized.wgConfig?.routerTunnelIp && vpnCableSubnet
      ? [
        '# ===== WireGuard VPN =====',
        `:if ([:len [/interface wireguard find name="wg-hq"]] = 0) do={`,
        `    /interface wireguard add name=wg-hq listen-port=${normalized.wgConfig.listenPort || 51820} private-key="${normalized.wgConfig.privateKey}" comment="HQ INVESTMENT VPN Interface"`,
        `} else={`,
        `    /interface wireguard set [find name="wg-hq"] private-key="${normalized.wgConfig.privateKey}"`,
        `}`,
        `:if ([:len [/interface list member find list="hq-mgmt" interface="wg-hq"]] = 0) do={`,
        `    /interface list member add list="hq-mgmt" interface="wg-hq" comment="HQ INVESTMENT VPN management"`,
        `}`,
        `:foreach addr in=[/ip address find interface="wg-hq"] do={ /ip address remove $addr }`,
        `/ip address add address="${normalized.wgConfig.routerTunnelIp}/24" interface=wg-hq comment="HQ INVESTMENT VPN Address"`,
        `:if ([:len [/interface wireguard peers find interface="wg-hq" public-key="${normalized.wgConfig.peerPublicKey}"]] = 0) do={`,
        `    /interface wireguard peers add interface=wg-hq public-key="${normalized.wgConfig.peerPublicKey}" allowed-address="${vpnCableSubnet}" endpoint-address="${normalized.wgConfig.serverEndpoint || 'YOUR_SERVER_IP'}" endpoint-port=${normalized.wgConfig.listenPort || 51820} persistent-keepalive=25s comment="HQ INVESTMENT ISP Server"`,
        `} else={`,
        `    /interface wireguard peers set [find interface="wg-hq" public-key="${normalized.wgConfig.peerPublicKey}"] allowed-address="${vpnCableSubnet}" endpoint-address="${normalized.wgConfig.serverEndpoint || 'YOUR_SERVER_IP'}" endpoint-port=${normalized.wgConfig.listenPort || 51820} persistent-keepalive=25s`,
        `}`,
        `:if ([:len [/ip route find dst-address="${vpnCableSubnet}" gateway="wg-hq"]] = 0) do={`,
        `    /ip route add dst-address="${vpnCableSubnet}" gateway=wg-hq comment="WireGuard route - HQ INVESTMENT"`,
        `}`,
        '/log info "WireGuard VPN configured — handshake will initiate via persistent-keepalive=25s"',
      ]
      : []),
    '',

    // ── L2TP/PPP VPN server (optional user VPN — distinct from WireGuard) ─────
    ...(normalized.vpnEnabled &&
      normalized.vpnProtocol &&
      normalized.vpnPoolStart &&
      normalized.vpnPoolEnd
      ? [
        '# ===== VPN Server (L2TP/PPP) =====',
        ...(normalized.vpnProtocol === 'L2TP' || normalized.vpnMode === 'hybrid'
          ? [
            `/ip pool add name="${vpnPoolName}" ranges=${normalized.vpnPoolStart}-${normalized.vpnPoolEnd}`,
            `/ppp profile add name="${vpnProfile}" local-address=${normalized.pppoeLocalAddress || normalized.hotspotLocalAddress} remote-address="${vpnPoolName}" dns-server=${normalized.vpnDns ?? '8.8.8.8'}`,
            `/interface l2tp-server server set enabled=yes use-ipsec=yes ipsec-secret="${normalized.ipsecSecret ?? ''}" default-profile="${vpnProfile}"`,
          ]
          : []),
        ...((normalized.vpnSecrets ?? []).length > 0
          ? (normalized.vpnSecrets ?? []).map(
            (s) =>
              `/ppp secret add name="${s.username}" password="${s.password}" service=${(s.protocol ?? normalized.vpnProtocol ?? 'l2tp').toLowerCase()} profile="${vpnProfile}"${s.localAddress ? ` local-address=${s.localAddress}` : ''}${s.remoteAddress ? ` remote-address=${s.remoteAddress}` : ''}`,
          )
          : []),
      ]
      : []),
    '',

    // ── PHASE 6: RADIUS Client ────────────────────────────────────────────────
    ...(hasBridgeInterfaces
      ? [
        '# ===== PHASE 6: RADIUS Client =====',
        `:if ([:len [/radius find where address="${normalized.radiusAddress}"]] = 0) do={`,
        `  /radius add service=hotspot,ppp address=${normalized.radiusAddress} secret="${normalized.radiusSecret}" authentication-port=1812 accounting-port=1813 timeout=3s`,
        '}',
        '/radius incoming set accept=yes port=3799',
        '/ppp aaa set use-radius=yes accounting=yes',
        '',
      ]
      : [
        '# BLOCKED_BY_DEPENDENCY: RADIUS skipped — no bridge configured.',
        '',
      ]),

    // ── PHASE 8: Walled Garden ────────────────────────────────────────────────
    ...(hasBridgeInterfaces
      ? [
        '# ===== PHASE 8: Walled Garden =====',
        `:if ([:len [/ip hotspot walled-garden find where dst-host="${normalized.apiHost}"]] = 0) do={ /ip hotspot walled-garden add dst-host="${normalized.apiHost}" action=allow comment="Billing Portal" }`,
        `:if ([:len [/ip hotspot walled-garden ip find where dst-address="${normalized.hotspotLocalAddress}"]] = 0) do={ /ip hotspot walled-garden ip add dst-address="${normalized.hotspotLocalAddress}" action=accept comment="Hotspot Gateway" }`,
        `:if ([:len [/ip hotspot walled-garden ip find where dst-address="${normalized.radiusAddress}"]] = 0) do={ /ip hotspot walled-garden ip add dst-address="${normalized.radiusAddress}" action=accept comment="Billing Portal IP" }`,
        ...(normalized.wgConfig?.routerTunnelIp
          ? [
            `:if ([:len [/ip hotspot walled-garden ip find where dst-address="${normalized.wgConfig.routerTunnelIp.split('.').slice(0, 3).join('.')}.0/24"]] = 0) do={ /ip hotspot walled-garden ip add dst-address="${normalized.wgConfig.routerTunnelIp.split('.').slice(0, 3).join('.')}.0/24" action=accept comment="VPN Subnet" }`,
          ]
          : []),
        // DEFECT-5 FIX: buildHotspotFlowEnforcementLines called ONLY here,
        // inside the hasBridgeInterfaces guard. $targetBridge is in scope.
        ...buildHotspotFlowEnforcementLines('$targetBridge'),
        '',
      ]
      : [
        '# BLOCKED_BY_DEPENDENCY: Walled Garden skipped — no bridge configured.',
        '',
      ]),

    // ── PHASE 9: DROP WAN — FINAL, only when WireGuard is confirmed ───────────
    '# ===== PHASE 9: Restrictive WAN Firewall (conditional on wg-hq) =====',
    '# DEFECT-4 FIX: DROP WAN input is ONLY applied when wg-hq exists and is in',
    '# the hq-mgmt interface list, proving management connectivity is preserved.',
    '# If wg-hq is absent, a log warning is emitted and NO drop rules are added.',
    ':if ([:len [/interface wireguard find name="wg-hq"]] > 0) do={',
    '    :if ([:len [/interface list member find list="hq-mgmt" interface="wg-hq"]] > 0) do={',
    '        :if ([:len [/ip firewall filter find where comment="Allow WireGuard UDP from WAN"]] = 0) do={',
    `            /ip firewall filter add chain=input action=accept protocol=udp dst-port=51820 in-interface-list=WAN comment="Allow WireGuard UDP from WAN"`,
    '        }',
    '        :if ([:len [/ip firewall filter find where comment="Block HQ INVESTMENT Management Ports (non-VPN)"]] = 0) do={',
    '            /ip firewall filter add chain=input action=drop protocol=tcp dst-port=80,443,8291 in-interface-list=WAN comment="Block HQ INVESTMENT Management Ports (non-VPN)"',
    '        }',
    '        :if ([:len [/ip firewall filter find where comment="Drop WAN input - HQ INVESTMENT"]] = 0) do={',
    '            /ip firewall filter add chain=input in-interface-list=WAN action=drop comment="Drop WAN input - HQ INVESTMENT"',
    '        }',
    '        /log info "HQ INVESTMENT: Restrictive WAN firewall applied. Router management is VPN-only. WireGuard is open."',
    '    } else={',
    '        /log warning "HQ INVESTMENT: wg-hq found but NOT in hq-mgmt. DROP WAN skipped for safety. Re-run after VPN is verified."',
    '    }',
    '} else={',
    '    /log warning "HQ INVESTMENT: wg-hq interface not found. DROP WAN was NOT applied. Run Auto-Push or configure WireGuard, then re-run this phase."',
    '}',
    '',

    // ── Configuration complete ─────────────────────────────────────────────────
    '# ===== Configuration Complete =====',
    '/log info "HQ INVESTMENT: Router Setup Wizard script completed."',
    ...(hasBridgeInterfaces
      ? []
      : [
        '/log warning "HQ INVESTMENT: Hotspot/PPPoE services were NOT configured (BLOCKED_BY_DEPENDENCY: no LAN interfaces selected)."',
      ]),
  ];

  return lines.filter((line) => line !== '').join('\n');
}
